package pri.simon.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.simon.bean.ArticleTag;
import pri.simon.bean.ArticleTagExample;

public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    long countByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int deleteByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int insert(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int insertSelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    List<ArticleTag> selectByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    ArticleTag selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArticleTag record);
}