package pri.simon.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.simon.bean.AttentionUser;
import pri.simon.bean.AttentionUserExample;
import pri.simon.bean.AttentionUserKey;

public interface AttentionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    long countByExample(AttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int deleteByExample(AttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AttentionUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int insert(AttentionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int insertSelective(AttentionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    List<AttentionUser> selectByExample(AttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    AttentionUser selectByPrimaryKey(AttentionUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AttentionUser record, @Param("example") AttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AttentionUser record, @Param("example") AttentionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AttentionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttentionUser record);
}