package pri.simon.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pri.simon.bean.AttentionArticle;
import pri.simon.bean.AttentionArticleExample;

public interface AttentionArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    long countByExample(AttentionArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int deleteByExample(AttentionArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer attentionArticleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int insert(AttentionArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int insertSelective(AttentionArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    List<AttentionArticle> selectByExample(AttentionArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    AttentionArticle selectByPrimaryKey(Integer attentionArticleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AttentionArticle record, @Param("example") AttentionArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AttentionArticle record, @Param("example") AttentionArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AttentionArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attention_article_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttentionArticle record);
}