package pri.simon.bean;

public class admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user.passward
     *
     * @mbg.generated
     */
    private String passward;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.admin_id
     *
     * @return the value of admin_user.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.admin_id
     *
     * @param adminId the value for admin_user.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.username
     *
     * @return the value of admin_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.username
     *
     * @param username the value for admin_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user.passward
     *
     * @return the value of admin_user.passward
     *
     * @mbg.generated
     */
    public String getPassward() {
        return passward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user.passward
     *
     * @param passward the value for admin_user.passward
     *
     * @mbg.generated
     */
    public void setPassward(String passward) {
        this.passward = passward == null ? null : passward.trim();
    }
}