package pri.simon.bean;

public class ArticleTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.article_name
     *
     * @mbg.generated
     */
    private String articleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.tag_id
     *
     * @return the value of article_tag.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.tag_id
     *
     * @param tagId the value for article_tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.user_id
     *
     * @return the value of article_tag.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.user_id
     *
     * @param userId the value for article_tag.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.article_name
     *
     * @return the value of article_tag.article_name
     *
     * @mbg.generated
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.article_name
     *
     * @param articleName the value for article_tag.article_name
     *
     * @mbg.generated
     */
    public void setArticleName(String articleName) {
        this.articleName = articleName == null ? null : articleName.trim();
    }
}