package pri.simon.bean;

public class AttentionUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_user.user_tag_id
     *
     * @mbg.generated
     */
    private Integer userTagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_user.user_id
     *
     * @return the value of attention_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_user.user_id
     *
     * @param userId the value for attention_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_user.user_tag_id
     *
     * @return the value of attention_user.user_tag_id
     *
     * @mbg.generated
     */
    public Integer getUserTagId() {
        return userTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_user.user_tag_id
     *
     * @param userTagId the value for attention_user.user_tag_id
     *
     * @mbg.generated
     */
    public void setUserTagId(Integer userTagId) {
        this.userTagId = userTagId;
    }
}