package pri.simon.bean;

public class AttentionUser extends AttentionUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_user.attention_user_id
     *
     * @mbg.generated
     */
    private Integer attentionUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_user.if_attention
     *
     * @mbg.generated
     */
    private Integer ifAttention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_user.attention_user_id
     *
     * @return the value of attention_user.attention_user_id
     *
     * @mbg.generated
     */
    public Integer getAttentionUserId() {
        return attentionUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_user.attention_user_id
     *
     * @param attentionUserId the value for attention_user.attention_user_id
     *
     * @mbg.generated
     */
    public void setAttentionUserId(Integer attentionUserId) {
        this.attentionUserId = attentionUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_user.if_attention
     *
     * @return the value of attention_user.if_attention
     *
     * @mbg.generated
     */
    public Integer getIfAttention() {
        return ifAttention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_user.if_attention
     *
     * @param ifAttention the value for attention_user.if_attention
     *
     * @mbg.generated
     */
    public void setIfAttention(Integer ifAttention) {
        this.ifAttention = ifAttention;
    }
}