package pri.simon.bean;

public class AttentionArticle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_article_list.attention_article_id
     *
     * @mbg.generated
     */
    private Integer attentionArticleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_article_list.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_article_list.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attention_article_list.if_attention
     *
     * @mbg.generated
     */
    private Integer ifAttention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_article_list.attention_article_id
     *
     * @return the value of attention_article_list.attention_article_id
     *
     * @mbg.generated
     */
    public Integer getAttentionArticleId() {
        return attentionArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_article_list.attention_article_id
     *
     * @param attentionArticleId the value for attention_article_list.attention_article_id
     *
     * @mbg.generated
     */
    public void setAttentionArticleId(Integer attentionArticleId) {
        this.attentionArticleId = attentionArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_article_list.user_id
     *
     * @return the value of attention_article_list.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_article_list.user_id
     *
     * @param userId the value for attention_article_list.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_article_list.article_id
     *
     * @return the value of attention_article_list.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_article_list.article_id
     *
     * @param articleId the value for attention_article_list.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attention_article_list.if_attention
     *
     * @return the value of attention_article_list.if_attention
     *
     * @mbg.generated
     */
    public Integer getIfAttention() {
        return ifAttention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attention_article_list.if_attention
     *
     * @param ifAttention the value for attention_article_list.if_attention
     *
     * @mbg.generated
     */
    public void setIfAttention(Integer ifAttention) {
        this.ifAttention = ifAttention;
    }
}