package pri.simon.bean;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_id
     *
     * @mbg.generated
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_path
     *
     * @mbg.generated
     */
    private String photoPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_id
     *
     * @return the value of photo.photo_id
     *
     * @mbg.generated
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_id
     *
     * @param photoId the value for photo.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.user_id
     *
     * @return the value of photo.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.user_id
     *
     * @param userId the value for photo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_path
     *
     * @return the value of photo.photo_path
     *
     * @mbg.generated
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_path
     *
     * @param photoPath the value for photo.photo_path
     *
     * @mbg.generated
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath == null ? null : photoPath.trim();
    }
}