package pri.simon.bean;

public class UserTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.user_tag_id
     *
     * @mbg.generated
     */
    private Integer userTagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.user_tag_name
     *
     * @mbg.generated
     */
    private String userTagName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.user_tag_id
     *
     * @return the value of user_tag.user_tag_id
     *
     * @mbg.generated
     */
    public Integer getUserTagId() {
        return userTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.user_tag_id
     *
     * @param userTagId the value for user_tag.user_tag_id
     *
     * @mbg.generated
     */
    public void setUserTagId(Integer userTagId) {
        this.userTagId = userTagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.user_tag_name
     *
     * @return the value of user_tag.user_tag_name
     *
     * @mbg.generated
     */
    public String getUserTagName() {
        return userTagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.user_tag_name
     *
     * @param userTagName the value for user_tag.user_tag_name
     *
     * @mbg.generated
     */
    public void setUserTagName(String userTagName) {
        this.userTagName = userTagName == null ? null : userTagName.trim();
    }
}